### ISSUE TITLE
ml-aoi extension schema page does not exists

### ISSUE THREAD

**Issue by raster-blaster** [stac-extensions/ml-aoi#9]
I am truing to access the extension schema page at `https://stac-extensions.github.io/ml-aoi/v0.1.0/schema.json` But its giving me 404 error, page does not exists.
Could you please look into this.

**Comment by fmigneault** [comment]
The extension is not released yet (still in `proposal`). This has to be accepted by the STAC Steering Committee.

@m-mohr Want to add this as an action item?

**Comment by m-mohr** [comment]
The PSC doesn't need to be involved. You can release as you like. If you are not sure about the status yet, consider starting with 0.x.x versions instead of releasing 1.0.0 directly.

**Comment by fmigneault** [comment]
Sorry if I wasn't clear. My request is about moving it to stable maturity and specifically, to make the "official" link https://stac-extensions.github.io/ml-aoi/v0.1.0/schema.json available. 

There is no update planned for ML-AOI JSON-schema, and there wasn't any update to it for a while.
I am working on https://github.com/stac-extensions/ml-aoi to provide Python interfaces, but they are based completely on the current JSON-schema definitions without any change to it. If anything needs to change later on, I would consider it a future release.

**Comment by m-mohr** [comment]
To make the "official" link https://stac-extensions.github.io/ml-aoi/v0.1.0/schema.json available you just create a release on GitHub. So as far as I see you can just create a release (tag and version: v0.1.0) and then the schema will become available a couple minutes later.

The maturity will stay in proposal until our annual update will take place and then it's updated according to the Extension [Maturity Classification](https://github.com/radiantearth/stac-spec/tree/master/extensions/README.md#extension-maturity).

**Comment by raster-blaster** [comment]
The schema link is active and working. Thanks for fixing this.
